export class Post {
    constructor(
        public id: number,
        public pk: number,
        public user_id: number,
        public profile_id: number,
        public email: string,
        public profile: any,
        public name: string,
        public date_posted: Date,
        public category: string,
        public content_name: string,
        public content_image: any,
        public video: any,
        public description: string,
        public comments: string,
        public likes: any,
        public student: any,
        public student_id: number,
        public technical_mentor_id: number,
        public content: string,
        public session: any,
        public module: any,
        public session_id: number,
        public module_id: number,
        public comment_id: number,
        public body: string,
        public bio: string,
        public profile_pic: any,
    ) { }

}
